name: test
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci --ignore-scripts --no-audit
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci --no-audit
      - run: npm test
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci --no-audit
      - run: npm run build
